name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Snake Animation
      - name: Generate snake animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Amirtoteles
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Build and deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: output
          folder: dist
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NODE_VERSION: 16.x

